# model_name: "gpt-3.5-turbo"
model_name: "gpt-4o"
model_name_tools: "gpt-4o"
model_name_combine_agent: "gpt-4o" 
climatemodel_name: "tco1279"
llmModeKey: "agent_llm" #"agent_llm" #"direct_llm"
use_high_resolution_climate_model: true
use_smart_agent: false
climate_model_input_files:
  climatology_IFS_9-FESOM_5-production_2020x_compressed.nc:
    file_name: './data/IFS_9-FESOM_5-production/climatology_IFS_9-FESOM_5-production_2020x_compressed.nc'
    years_of_averaging: '2020-2029'
    description: 'The nextGEMS pre-final simulations for years 2030x..'
    coordinate_system: 'healpix'
    source: 'The nextGEMS pre-final simulations build on cycle 3 experience plus adaptations for multi-decadal experiments. Model: FS_9-FESOM_5-production, 2020-2050 .'
    is_main: true
  climatology_IFS_9-FESOM_5-production_2030x_compressed.nc:
    file_name: './data/IFS_9-FESOM_5-production/climatology_IFS_9-FESOM_5-production_2030x_compressed.nc'
    years_of_averaging: '2030-2039'
    description: 'The nextGEMS pre-final simulations for years 2030x.'
    coordinate_system: 'healpix'
    source: 'The nextGEMS pre-final simulations build on cycle 3 experience plus adaptations for multi-decadal experiments. Model: FS_9-FESOM_5-production, 2020-2050 .'
  climatology_IFS_9-FESOM_5-production_2040x_compressed.nc:
    file_name: './data/IFS_9-FESOM_5-production/climatology_IFS_9-FESOM_5-production_2040x_compressed.nc'
    years_of_averaging: '2040-2049'
    description: 'The nextGEMS pre-final simulations for years 2040x.'
    coordinate_system: 'healpix' 
    source: 'The nextGEMS pre-final simulations build on cycle 3 experience plus adaptations for multi-decadal experiments. Model: FS_9-FESOM_5-production, 2020-2050 .'
climate_model_variable_mapping:
    Temperature: mean2t
    Total Precipitation: tp
    Wind U: wind_u
    Wind V: wind_v   
data_settings:
    data_path: "../climsight/data/"
    historical: "2000" 
    projection: "2090" 
variable_mappings:
    Temperature: "2t" 
    Precipitation: "precip"
    u_wind: "10u"  
    v_wind: "10v" 
dimension_mappings:
    latitude: "lat"
    longitude: "lon"
    time: "time_counter" #"month"
rag_settings:
    rag_activated: True
    embedding_model: "text-embedding-3-large"
    chroma_path_ipcc: "rag_db/ipcc_reports"
    chroma_path_general: "rag_db/general_reports"
    document_path: './data/general_reports/' # or ipcc_text_reports
    chunk_size: 2000
    chunk_overlap: 200
    separators: [" ", ",", "\n"]
rag_template: |
    You are an assistant specialized in extracting information from scientific reports for a given location. 

    Instructions:
    1. **Relevance & Conciseness**: Provide the most relevant and concise information that directly answers the question.
    2. **Regional Specificity**: 
    - If information for the specified region is available, present it clearly.
    - If not, offer a general answer and explicitly state that it does not pertain specifically to the given location or country.
    3. **Avoid Unrelated Details**: Include only information pertinent to the question and location.
    4. **Geographical Consideration**: Take into account the geographical context of the provided location.
    5. **Uncertainty Handling**: 
    - If the answer is not directly available from the context, provide the best possible answer based solely on the provided context, and indicate any assumptions or generalizations made within it.
    - Limit your response to the information given; do not include information generated outside of the provided context.
    - Only respond with None if the question is completely unrelated to the context or location provided.
    - Do not provide extended explanations or comments in this case. 

    Content from reports: {context}
    Location: {location}
    Question: {question}
coastline_shapefile: "../climsight/data/natural_earth/coastlines/ne_10m_coastline.shp"
haz_path: '../climsight/data/natural_hazards/pend-gdis-1960-2018-disasterlocations.csv'
pop_path: '../climsight/data/population/WPP2022_Demographic_Indicators_Medium.csv'
natural_e_path: './data/natural_earth/'
distance_from_event: 5.0
lat_default: 52.5240
lon_default: 13.3700
year_step: 10
start_year: 1980
end_year: null
system_role: |
    You are the system that helps people evaluate the impact of climate change on decisions they are taking, 
    such as installing wind turbines, solar panels, constructing buildings, developing parking lots, opening shops, 
    or purchasing cropland. Your analysis should focus on the local level, providing advice tailored to the specific 
    location and scenario. If IPCC reports or other credible references are included, incorporate that data and 
    cite it. Draw on any country-specific policies and regulations mentioned, as well as any environmental and 
    climate-related parameters provided.

    You will be given a human question, followed by additional information and data sources—such as JSON tables, 
    textual references, and environmental parameters—collected through a retrieval process. These materials 
    represent your authoritative data. Always rely on the given data and text sources for your analysis; do not 
    use or invent figures not present in the provided materials. You do not need to include all variables if their 
    impact is negligible, but do integrate important figures or parameters into a narrative format.

    Your response should be a coherent narrative rather than a terse summary or a simple list of variables. 
    Incorporate the provided numerical data into meaningful sentences and, if helpful for clarity, use a Markdown 
    table to present key quantitative parameters. Avoid overly brief answers. Do not use headings at level 1 or 2. 
    Do not simply restate input data; instead, synthesize it into a rich, context-aware assessment of potential 
    risks, benefits, and recommendations. The goal is a detailed, evidence-based, and location-specific narrative 
    that guides decision-making in the context of a changing climate.
