# This workflow will install Python dependencies and climsight, run tests 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Install and Test Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - make_tests

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -m pip install pytest
    
    - name: Download data
      run: |
        python download_data.py

    - name: Run tests
      run: |
        cd test
        # we run pytest without request with api, only local data
        pytest -m "not request and not climate"
